// Refresh the Google rating (score + review count) before every build.
//
// Uses the official Places API (New) — never scraping. The `rating` and
// `userRatingCount` fields are Enterprise-SKU: 1,000 free calls/month; a
// daily build uses ~30, so this costs ₹0.
//
// Setup (one-time, see RATING-AUTOUPDATE.md):
//   1. Google Cloud → enable "Places API (New)" → create an API key.
//   2. Find your Place ID:  GOOGLE_PLACES_API_KEY=xxx node scripts/fetch-rating.mjs --find
//   3. Set GOOGLE_PLACES_API_KEY + GOOGLE_PLACE_ID env vars in Vercel.
//
// Behaviour without the env vars: prints a note and exits 0 — the committed
// fallback values in src/data/rating.gen.js are used. Never breaks a build.

import { readFileSync, writeFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const KEY = process.env.GOOGLE_PLACES_API_KEY
const PLACE_ID = process.env.GOOGLE_PLACE_ID

// ---- one-time helper: find the Place ID ----
if (process.argv.includes('--find')) {
  if (!KEY) { console.error('Set GOOGLE_PLACES_API_KEY first.'); process.exit(1) }
  const res = await fetch('https://places.googleapis.com/v1/places:searchText', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'X-Goog-Api-Key': KEY,
      'X-Goog-FieldMask': 'places.id,places.displayName,places.formattedAddress,places.rating,places.userRatingCount',
    },
    body: JSON.stringify({ textQuery: 'Zaid Electronics Balaji Mandir Rd Cheeta Camp Trombay Mumbai' }),
  })
  const data = await res.json()
  for (const p of data.places || []) {
    console.log(`\nPLACE ID: ${p.id}`)
    console.log(`  name:   ${p.displayName?.text}`)
    console.log(`  addr:   ${p.formattedAddress}`)
    console.log(`  rating: ${p.rating}★ · ${p.userRatingCount} reviews`)
  }
  if (!data.places?.length) console.log('No match found:', JSON.stringify(data).slice(0, 300))
  process.exit(0)
}

// ---- normal mode: refresh values ----
if (!KEY || !PLACE_ID) {
  console.log('fetch-rating: skipped (GOOGLE_PLACES_API_KEY / GOOGLE_PLACE_ID not set) — using committed fallback values.')
  process.exit(0)
}

try {
  const res = await fetch(`https://places.googleapis.com/v1/places/${PLACE_ID}`, {
    headers: { 'X-Goog-Api-Key': KEY, 'X-Goog-FieldMask': 'rating,userRatingCount' },
  })
  if (!res.ok) throw new Error(`HTTP ${res.status}: ${(await res.text()).slice(0, 200)}`)
  const { rating, userRatingCount } = await res.json()
  if (typeof rating !== 'number' || typeof userRatingCount !== 'number') {
    throw new Error('rating fields missing in response')
  }

  const score = rating.toFixed(1)
  const rounded = Math.max(10, Math.floor(userRatingCount / 10) * 10)

  // 1) the generated module (feeds React components + landing-page generator)
  writeFileSync(join(ROOT, 'src/data/rating.gen.js'),
`// AUTO-GENERATED by scripts/fetch-rating.mjs — do not edit by hand.
// These are fallback values, used whenever GOOGLE_PLACES_API_KEY is not
// configured (e.g. local builds). On Vercel the fetch script overwrites this
// file with the live Google rating before every build.
export const LIVE_RATING = {
  score: ${score},
  count: ${userRatingCount},
  fetchedAt: '${new Date().toISOString()}',
}
`)

  // 2) patch static files that carry the numbers as literal text.
  //    Generic patterns so this works no matter what the previous values were.
  const patch = (rel) => {
    const p = join(ROOT, rel)
    let t = readFileSync(p, 'utf8')
    const before = t
    t = t.replace(/"ratingValue":\s*"\d\.\d"/g, `"ratingValue": "${score}"`)
    t = t.replace(/"reviewCount":\s*"\d+"/g, `"reviewCount": "${userRatingCount}"`)
    t = t.replace(/\d\.\d★/g, `${score}★`)
    t = t.replace(/\b\d{2,5}\+ (reviews|customers)/g, `${rounded}+ $1`)
    if (t !== before) { writeFileSync(p, t); console.log(`fetch-rating: patched ${rel}`) }
  }
  patch('index.html')
  patch('public/llms.txt')

  console.log(`fetch-rating: live Google rating ${score}★ · ${userRatingCount} reviews (shown as "${rounded}+")`)
} catch (err) {
  console.warn('fetch-rating: FAILED — keeping previous values. Reason:', err.message)
  process.exit(0) // never break the build over a rating refresh
}
